// export enum ModuleIdList {
//     Dashboard = 1,
//     Registration = 2,
//     SpecialOffers = 3,
//     Notification = 4,
//     Users = 5,
//     MobileOTP = 6,
//     Reports = 7,
//     Brand = 8,
//     ShowroomCars = 9,
//     Catalogue = 10,
//     AppVersion = 11,
//     CarShowroomDetails = 12,
//     UserRole = 13,
//     Module = 14,
//     Settings = 15,
//     CarCity = 16,
//     UserPrivilege = 17,
//     LoginLog = 18,
//     PortalUser = 19,
//     ShowroomProfile = 20,
//     ShowroomCategory = 21,
//     CarOwerType = 33,
//     Model = 22,
//     Geaccount = 35,
//     Gecampaign = 36,
//     CampaignsType = 37,
//     Gecontact = 38,
//     Lead = 39,
//     Opportunity = 40,
//     Quote = 41,
//     Salesorder = 42,
//     CashRequest = 45,
//     TestDrive = 49,
//     LuckyCategory = 51,
//     LuckyInventory = 52,
//     LuckykeyManagement = 53,
//     'ACTIVE CARS DETAILS REPORT' = 65,
//     'ADVANCE REPORT' = 66,
//     'BRAND WISE CAR DETAILS REPORT' = 67,
//     'LEADS REPORT' = 68,
//     'OPPORTUNITY REPORT' = 69,
//     'OPPORTUNITY CAR DETAIL REPORT' = 70,
//     'QUOTATION REPORT' = 71,
//     'QUOTATION CAR DETAIL REPORT' = 72,
//     'SALES ORDER REPORT' = 73,
//     'SALES ORDER CAR DETAILS REPORT' = 74,
//     'EXPENSE REPORT' = 75,
//     'CONSIGNMENT REPORT' = 76,
//     'CARS DETAILS REPORT' = 77,
//     'SALES REPORT' = 78,
//     'SOLD CAR SALES REPORT' = 79,
//     'ACTIVE CAR SALES REPORT' = 80,
//     'PRINT DOCUMENT HISTORY' = 81,
//     'GIFT DRAW INVENTORY' = 82,
//     'KEY DRAW DETAILS' = 83,
//     'MOBILE APP SHARE LINK REPORT' = 84,
//     'CASH REQUEST REPORT' = 85,
//     'SHARED CAR SALES REPORT' = 87,
//     'Consignment' = 88,
//     'Expense' = 89,
//     SalesorderActivity = 90,
//     Advance = 97,
//     LeadActivity = 98,
//     OpportunityActivity = 99,
//     QuoteActivity = 100,
//     OpportunityTestDrive = 101,
//     ConsignmentMainMenu = 102,
//     PurchaseAgreement = 105,
//     ExpenseMainMenu = 111,
//     AdvanceMainMenu = 112,
//     PurchaseAgreementainMenu = 113,
//     CRMUSER = 31,
//     ExpenseType = 34,
//     Stage = 43,  AppInternalVersion = 103,
// }

// live





export enum ModuleIdList {
    Dashboard = 1,
    Registration = 2,
    SpecialOffers = 3,
    Notification = 4,
    Users = 5,
    MobileOTP = 6,
    Reports = 7,
    Brand = 8,
    ShowroomCars = 9,
    Catalogue = 10,
    AppVersion = 11,
    CarShowroomDetails = 12,
    UserRole = 13,
    Module = 14,
    Settings = 15,
    CarCity = 16,
    UserPrivilege = 17,
    LoginLog = 18,
    PortalUser = 19,
    ShowroomProfile = 20,
    ShowroomCategory = 21,
    CarOwerType = 33,
    Model = 22,
    Geaccount = 35,
    Gecampaign = 36,
    CampaignsType = 37,
    Gecontact = 38,
    Lead = 39,
    Opportunity = 40,
    Quote = 41,
    Salesorder = 42,
    CashRequest = 45,
    TestDrive = 49,
    LuckyCategory = 51,
    LuckyInventory = 52,
    VehicleAppraisal = 57,
    LuckykeyManagement = 53,
    'ACTIVE CARS DETAILS REPORT' = 62,
    'ADVANCE REPORT' = 63,
    'BRAND WISE CAR DETAILS REPORT' = 64,
    'LEADS REPORT' = 65,
    'OPPORTUNITY REPORT' = 66,
    'OPPORTUNITY CAR DETAIL REPORT' = 67,
    'QUOTATION REPORT' = 68,
    'QUOTATION CAR DETAIL REPORT' = 69,
    'SALES ORDER REPORT' = 70,
    'SALES ORDER CAR DETAILS REPORT' = 71,
    'EXPENSE REPORT' = 72,
    'CONSIGNMENT REPORT' = 73,
    'CARS DETAILS REPORT' = 74,
    'SALES REPORT' = 75,
    'SOLD CAR SALES REPORT' = 76,
    'ACTIVE CAR SALES REPORT' = 77,
    'PRINT DOCUMENT HISTORY' = 78,
    'GIFT DRAW INVENTORY' = 79,
    'KEY DRAW DETAILS' = 80,
    'MOBILE APP SHARE LINK REPORT' = 81,
    'CASH REQUEST REPORT' = 82,
    'SHARED CAR SALES REPORT' = 84,
    'Consignment' = 56,
    'Expense' = 86,
    DriverTracking = 108,
    SalesorderActivity = 98,
    Advance = 88,
    LeadActivity = 96,
    OpportunityActivity = 95,
    QuoteActivity = 97,
    OpportunityTestDrive = 100,
    ConsignmentMainMenu = 91,
    PurchaseAgreement = 93,
    ExpenseMainMenu = 89,
    AdvanceMainMenu = 87,
    PurchaseAgreementainMenu = 94,
    CRMUSER = 31,
    ExpenseType = 34,
    Stage = 43,
    AppInternalVersion = 103,
    Event = 109,
    EventModuleField =110,
    EventModule =111,
    EventPlanner = 114,
    EventQrcode = 118,
    EventQuery= 112,
    EventTemplate  = 113,
    CRMModel = 120,
    RequestInspectionReport =121, 
    RequestInspectionReportMainMenu = 120
}


export enum RoleIdList {
    // Role
    ShowroomSalesman = 9,
    ShowroomManager = 10,
    Admin = 1,
    ShowroomSupervisor = 4,
    Accountant = 11,
    Finance = 12,
    FinanceManager = 13,
}

//Routing User Dashboard Redirection
export enum DashboardRedirection {
    "ADMINISTRATOR DASHBOARD" = "/dashboard",
    "PORTAL DASHBOARD" = "/dashboard/portal",
    "SHOWROOM SUPERVISOR DASHBOARD" = "/dashboard/showroom"
}

